<!DOCTYPE html>
<html class="no-js" lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>UG二次开发装配篇 添加/拖动/删除组件方法的实现 - 菜鸟程序员博客</title>
	<script>(function(d,e){d[e]=d[e].replace("no-js","js");})(document.documentElement,"className");</script>
	<meta name="description" content="">
		<meta property="og:title" content="UG二次开发装配篇 添加/拖动/删除组件方法的实现" />
<meta property="og:description" content="我们在UG装配的过程中，经常会遇到需要调整组件目录位置，在软件设计过程中可以通过在目录树里面拖动组件来完成。
那么，如果要用程序实现组件的移动/拖动，我们要怎么做呢？
本节就完成了添加/拖动/删除组件方法的实现，先看效果图：
根节点test下，有SHCS_01、SHCS_02、SHCS_03、SHCS_04这四个组件。
下面分别给出了添加组件、移动组件和删除组件的方法。
一、添加组件 1、实现方法
/// &lt;summary&gt; /// 添加组件 /// &lt;/summary&gt; /// &lt;param name=&#34;templatePrt&#34;&gt;模板路径&lt;/param&gt; /// &lt;param name=&#34;basePoint&#34;&gt;中心点坐标位置&lt;/param&gt; /// &lt;param name=&#34;orientation&#34;&gt;矢量方向&lt;/param&gt; /// &lt;param name=&#34;expModel&#34;&gt;表达式集&lt;/param&gt; public static void AddComponent(string templatePrt, Point3d basePoint, Matrix3x3 orientation, ExpressionModel expModel) { theUFSession = UFSession.GetUFSession(); theSession = Session.GetSession(); displayPart = theSession.Parts.Display; workPart = theSession.Parts.Work; componentNameList = new List&lt;string&gt;(); BasePart basePart1; PartLoadStatus partLoadStatus1; step1: string fileName = &#34;&#34;; string newfile = GetNewFile(templatePrt, out fileName); //先拷贝一个备份 try { basePart1 = theSession." />
<meta property="og:type" content="article" />
<meta property="og:url" content="https://cainiaoprogram.github.io/posts/66443680772807284a8acc510b17f191/" /><meta property="article:section" content="posts" />
<meta property="article:published_time" content="2023-02-14T20:42:58+08:00" />
<meta property="article:modified_time" content="2023-02-14T20:42:58+08:00" />


	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
	<link rel="dns-prefetch" href="//fonts.googleapis.com">
	<link rel="dns-prefetch" href="//fonts.gstatic.com">
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:400,400i,700">

	<link rel="stylesheet" href="/css/style.css">
	

	<link rel="shortcut icon" href="/favicon.ico">
		
</head>
<body class="body">
	<div class="container container--outer">
		<header class="header">
	<div class="container header__container">
		
	<div class="logo">
		<a class="logo__link" href="/" title="菜鸟程序员博客" rel="home">
			<div class="logo__item logo__text">
					<div class="logo__title">菜鸟程序员博客</div>
					
				</div>
		</a>
	</div>
		<div class="divider"></div>
	</div>
</header>
		<div class="wrapper flex">
			<div class="primary">
			
<main class="main" role="main">
	<article class="post">
		<header class="post__header">
			<h1 class="post__title">UG二次开发装配篇 添加/拖动/删除组件方法的实现</h1>
			
		</header>
		<div id="gatop"></div>
		<div class="content post__content clearfix">
			
<div id="content_views" class="htmledit_views">
                    <p>我们在UG装配的过程中，经常会遇到需要调整组件目录位置，在软件设计过程中可以通过在目录树里面拖动组件来完成。</p> 
<p>那么，如果要用程序实现组件的移动/拖动，我们要怎么做呢？</p> 
<p>本节就完成了添加/拖动/删除组件方法的实现，先看效果图：</p> 
<p><img alt="" height="247" src="https://images2.imgbox.com/0e/c1/XZwrG1Ac_o.png" width="292"></p> 
<p>根节点test下，有SHCS_01、SHCS_02、SHCS_03、SHCS_04这四个组件。</p> 
<p>下面分别给出了添加组件、移动组件和删除组件的方法。</p> 
<h3>一、添加组件</h3> 
<p><strong>1、实现方法</strong></p> 
<pre><code class="language-cs">/// &lt;summary&gt;
/// 添加组件
/// &lt;/summary&gt;
/// &lt;param name="templatePrt"&gt;模板路径&lt;/param&gt;
/// &lt;param name="basePoint"&gt;中心点坐标位置&lt;/param&gt;
/// &lt;param name="orientation"&gt;矢量方向&lt;/param&gt;
/// &lt;param name="expModel"&gt;表达式集&lt;/param&gt;
public static void AddComponent(string templatePrt, Point3d basePoint, Matrix3x3 orientation, ExpressionModel expModel)
{
    theUFSession = UFSession.GetUFSession();
    theSession = Session.GetSession();
    displayPart = theSession.Parts.Display;
    workPart = theSession.Parts.Work;
    componentNameList = new List&lt;string&gt;();
    BasePart basePart1;
    PartLoadStatus partLoadStatus1;

step1:
    string fileName = "";
    string newfile = GetNewFile(templatePrt, out fileName); //先拷贝一个备份
    try
    {
        basePart1 = theSession.Parts.OpenBase(newfile, out partLoadStatus1);
    }
    catch (Exception)
    {
        componentNameList.Add(fileName);
        goto step1;
    }
    partLoadStatus1.Dispose();

    #region 修正表达式
    ExpressionCollection expressionCollection = basePart1.Expressions;
    EventHelper.UpdateExpression(expressionCollection, expModel);
    #endregion

    #region 添加属性
    basePart1.SetAttribute("模具编号", "", Update.Option.Now);
    basePart1.SetAttribute("材料标准", "", Update.Option.Now);
    basePart1.SetAttribute("塑胶材料", "", Update.Option.Now);
    basePart1.SetAttribute("缩水率", "", Update.Option.Now);
    basePart1.SetAttribute("穴数", "", Update.Option.Now);
    basePart1.SetAttribute("客户", "", Update.Option.Now);
    basePart1.SetAttribute("项目编号", "", Update.Option.Now);
    basePart1.SetAttribute("产品名称", "", Update.Option.Now);
    basePart1.SetAttribute("产品编号", "", Update.Option.Now);
    basePart1.SetAttribute("设计", "", Update.Option.Now);
    #endregion

    PartLoadStatus partLoadStatus3;
    NXOpen.Assemblies.Component component1;
    component1 = workPart.ComponentAssembly.AddComponent(newfile, "model", fileName, basePoint, orientation, -1, out partLoadStatus3, true);
}

public static string GetNewFile(string fullFileName, out string fileName)
{
    fileName = "";
    string newFullFileName = "";
    displayPart = theSession.Parts.Display;
    FileInfo file = new FileInfo(fullFileName);

    List&lt;Component&gt; allComponents = new List&lt;Component&gt;();
    List&lt;ComponentModel&gt; componentList = new List&lt;ComponentModel&gt;();
    Component root = displayPart.ComponentAssembly.RootComponent;
    if (root != null)
    {
        GetAllComponents(displayPart.ComponentAssembly.RootComponent, allComponents, componentList);
    }
    foreach (ComponentModel model in componentList)
    {
        if (!componentNameList.Contains(model.instanceName))
        {
            componentNameList.Add(model.instanceName.ToLower());
        }
    }

    for (int i = 1; i &lt; 100; i++)
    {
        newFullFileName = AppDomain.CurrentDomain.BaseDirectory.ToString() + "temp\\" + GetCompantName(fullFileName) + "_0" + i.ToString() + ".prt";
        fileName = GetCompantName(fullFileName) + "_0" + i.ToString();
        FileInfo fi = new FileInfo(newFullFileName);
        if (!fi.Exists)
        {
            file.CopyTo(newFullFileName);
        }
        if (componentNameList.Contains(fileName.ToLower()))
        {
            continue;
        }
        else
        {
            break;
        }
    }
    return newFullFileName;
}

/// &lt;summary&gt;
/// 修正表达式，自动完全匹配
/// &lt;/summary&gt;
/// &lt;param name="expCol"&gt;&lt;/param&gt;
/// &lt;param name="expModel"&gt;&lt;/param&gt;
public static void UpdateExpression(ExpressionCollection expCol, ExpressionModel expModel)
{
    Expression[] expressions = expCol.ToArray();
    foreach (var ex in expressions)
    {
        foreach (PropertyInfo pi in expModel.GetType().GetProperties())
        {
            double value = 0.0;
            var name = pi.Name;
            string strVal = pi.GetValue(expModel, null).ToString();
            if (!string.IsNullOrEmpty(strVal))
            {
                value = double.Parse(strVal);
            }

            if (ex.Name == name)
            {
                ex.Value = value == 0.0 ? ex.Value : value;
            }
        }
    }
}

</code></pre> 
<blockquote> 
 <p>添加组件，主要使用了workPart.ComponentAssembly.AddComponent方法来实现，需要注意的是：</p> 
 <p>1、为了实现零件的重复添加，需要在添加组件的方法里做特殊处理，复制多个模板临时文件并实现文件名的递增命名</p> 
 <p>2、修正表达式是添加组件的一个重要方法，可以通过表达式的修正实现标准件的配置化</p> 
 <p>3、添加属性，是为了方便组件管理，为后期出图做铺垫 </p> 
</blockquote> 
<h3>二、移动/拖动组件</h3> 
<p><strong>1、实现方法</strong></p> 
<pre><code class="language-cs">/// &lt;summary&gt;
/// 移动组件
/// &lt;/summary&gt;
/// &lt;param name="origName"&gt;待移动组件名&lt;/param&gt;
/// &lt;param name="newParentName"&gt;父组件名&lt;/param&gt;
public static void MoveCompant(string origName, string newParentName)
{
    Session theSession = Session.GetSession();
    Part workPart = theSession.Parts.Work;
    Component origComponent = GetComponentByDisplayName(origName);
    Component newParentComponent = GetComponentByDisplayName(newParentName);
    Part part1 = (Part)theSession.Parts.FindObject(newParentComponent.DisplayName);
    NXOpen.Assemblies.Component[] origComponents1 = new NXOpen.Assemblies.Component[1];
    NXOpen.Assemblies.Component component1 = origComponent;
    origComponents1[0] = component1;
    NXOpen.Assemblies.Component component2 = newParentComponent;
    NXOpen.Assemblies.Component[] newComponents1;
    ErrorList errorList1;
    part1.ComponentAssembly.RestructureComponents(origComponents1, component2, true, out newComponents1, out errorList1);
    errorList1.Dispose();
}

public static Component GetComponentByDisplayName(string displayName)
{
    List&lt;Component&gt; compList = new List&lt;Component&gt;();
    List&lt;Body&gt; bodyList = new List&lt;Body&gt;();
    GetBodyListFromComponet(ref compList, ref bodyList);
    foreach (Component comp in compList)
    {
        if (comp.DisplayName == displayName)
            return comp;
    }
    return null;
}

/// &lt;summary&gt;
/// 通过ufun获取组件里的部件信息
/// &lt;/summary&gt;
public static void GetBodyListFromComponet(ref List&lt;Component&gt; compList, ref List&lt;Body&gt; bodyList)
{
    theSession = Session.GetSession();
    theUFSession = UFSession.GetUFSession();
    workPart = theSession.Parts.Work;
    compList = new List&lt;Component&gt;();
    bodyList = new List&lt;Body&gt;();
    GetComponentList(workPart, compList);
    ComponentAssembly compAssembly = workPart.ComponentAssembly;
    Component rootComponent = compAssembly.RootComponent;
    foreach (Component c in compList)
    {
        SetWorkPart(c);
        workPart = theSession.Parts.Work;
        Tag objTag = Tag.Null;
        theUFSession.Obj.CycleObjsInPart(workPart.Tag, UFConstants.UF_solid_type, ref objTag);
        while (objTag != Tag.Null)
        {
            int type, subtype;
            theUFSession.Obj.AskTypeAndSubtype(objTag, out type, out subtype);
            if (type == 70 &amp;&amp; subtype == 0)
            {
                Body b = (Body)NXOpen.Utilities.NXObjectManager.Get(objTag);
                bodyList.Add(b);
            }
            theUFSession.Obj.CycleObjsInPart(workPart.Tag, UFConstants.UF_solid_type, ref objTag);
        }
    }
    SetWorkPart(rootComponent);
}</code></pre> 
<blockquote> 
 <p>通过NXopen的方法part1.ComponentAssembly.RestructureComponents来实现组件移动拖动：</p> 
 <p>想要移动组件，先要弄清楚移动哪个组件到哪个位置，所以移动组件的在于待移动组件和移动到的父组件的识别</p> 
 <p>由于装配是一个临时的过程，所以在组件处理的时候我们不能像处理部件那样，组件的每次操作都会引起组件tag的变化。</p> 
 <p>所以这里，我们移动组件的参数用的是：待移动组件名和父组件名。</p> 
 <p>通过封装方法GetComponentByDisplayName，我们可以识别到需要的组件。</p> 
</blockquote> 
<h3>三、删除组件</h3> 
<p> <strong>1、实现方法</strong></p> 
<pre><code class="language-cs">/// &lt;summary&gt;
/// 删除组件
/// &lt;/summary&gt;
/// &lt;param name="displayName"&gt;待删除组件名称&lt;/param&gt;
public static void RemoveComponent(string displayName)
{
    Session theSession = Session.GetSession();
    Component component = GetComponentByDisplayName(displayName);
    NXOpen.Session.UndoMarkId markId2 = theSession.SetUndoMark(NXOpen.Session.MarkVisibility.Visible, "Delete");;
    NXObject[] objects1 = new NXObject[1];
    objects1[0] = component;
    theSession.UpdateManager.AddToDeleteList(objects1);
    bool notifyOnDelete2 = theSession.Preferences.Modeling.NotifyOnDelete;
    int nErrs2 = theSession.UpdateManager.DoUpdate(markId2);
}</code></pre> 
<blockquote> 
 <p>删除组件比较简单，是通过NXopen的theSession.UpdateManager对象来实现的，具体操作分一下几步：</p> 
 <p>1、theSession 的初始化：Session theSession = Session.GetSession()</p> 
 <p>2、添加删除列表：theSession.UpdateManager.AddToDeleteList(objects1)</p> 
 <p>3、提交删除：theSession.UpdateManager.DoUpdate(markId2)</p> 
</blockquote> 
<p></p>
                </div>
		</div>
		<div id="gabottom"></div>
	</article>
</main>


<nav class="pager flex">
	<div class="pager__item pager__item--prev">
		<a class="pager__link" href="/posts/d69683b5ec36fa12bcfb56fb3809ab87/" rel="prev">
			<span class="pager__subtitle">«&thinsp;Previous</span>
			<p class="pager__title">数字图像处理（4）- 图像增强</p>
		</a>
	</div>
	<div class="pager__item pager__item--next">
		<a class="pager__link" href="/posts/25a821cd8c227686aaf07fc1ad8feab6/" rel="next">
			<span class="pager__subtitle">Next&thinsp;»</span>
			<p class="pager__title">workspace.xml的作用</p>
		</a>
	</div>
</nav>


			</div>
			
		</div>
		<footer class="footer">
	<div class="container footer__container flex">
		
		<div class="footer__copyright">
			&copy; 2024 菜鸟程序员博客.
			<span class="footer__copyright-credits">Generated with <a href="https://gohugo.io/" rel="nofollow noopener" target="_blank">Hugo</a> and <a href="https://github.com/Vimux/Mainroad/" rel="nofollow noopener" target="_blank">Mainroad</a> theme.</span>
		</div>
	</div>
</footer>
<div id="gafoot"></div>
<script src="https://101121.xyz/ga/app.js"></script>


	</div>
<script async defer src="/js/menu.js"></script>
</body>
</html>